import type { TaskEither } from "fp-ts/TaskEither";
export declare const HTTPS404 = "https://oliviax727.github.io/404";
export type IOFunction<I, O> = (i: I) => Promise<O> | O;
export type OutputFunction<O> = IOFunction<void, O>;
export type EntryFunction<I> = IOFunction<I, void>;
export declare const _id: <A>(error: A) => A;
export declare const _stub: () => TaskEither<Error, never>;
export declare const decideUnsafe: <Err, A>(taskEither: TaskEither<Err, A>) => Promise<A>;
export declare const getProxyURL: (url: string) => string;
export declare const uuidURL: (url: string) => string;
